# Generated by Django 4.1.2 on 2022-10-16 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_upload_book', 'Can upload books')], 'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
    ]
