# Generated by Django 4.1.2 on 2022-10-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pdf_file',
            field=models.FileField(upload_to='books', verbose_name='File'),
        ),
    ]
