# Generated by Django 4.1.2 on 2022-10-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_book', '0003_rename_category_genre_alter_book_options_and_more'),
        ('api_book', '0004_rename_category_book_genre_alter_book_pdf_file'),
    ]

    operations = [
    ]
