# Generated by Django 4.1.2 on 2022-10-19 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_text', models.TextField(verbose_name='Review Text')),
                ('rating', models.SmallIntegerField(verbose_name='Rating')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_book.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': "User's Review",
                'verbose_name_plural': "Users' Reviews",
            },
        ),
        migrations.CreateModel(
            name='UserLibraryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('books_in_process', models.ManyToManyField(related_name='reading+', related_query_name='books_reading', to='api_book.book')),
                ('books_read', models.ManyToManyField(related_name='books+', related_query_name='books_read', to='api_book.book')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': "User's Library Activity",
                'verbose_name_plural': "Users' Library Activities",
            },
        ),
        migrations.CreateModel(
            name='UserHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.SmallIntegerField(verbose_name='Page number')),
                ('start_of_note', models.SmallIntegerField(verbose_name='Start position of the Note')),
                ('end_of_note', models.SmallIntegerField(verbose_name='End position of the Note')),
                ('note_text', models.TextField(verbose_name='Note Text')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_book.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': "User's Highlight",
                'verbose_name_plural': "Users' Highlights",
            },
        ),
        migrations.CreateModel(
            name='UserBookActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.SmallIntegerField(verbose_name='Current Page number')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_book.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': "User's Book Activity",
                'verbose_name_plural': "Users' Books Activities",
            },
        ),
    ]
